apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  MONGO_DB: journaldb
  SERVER_PORT: "8082"
  WEATHER_API_KEY: 803b8294a0746b24173afa72841674ff
  REDIS_HOST: redis-18120.c305.ap-south-1-1.ec2.redns.redis-cloud.com
  REDIS_PORT: "18120"
  KAFKA_BOOTSTRAP: pkc-9q8rv.ap-south-2.aws.confluent.cloud:9092
  KAFKA_GROUP_ID: journal-consumer-group
  CLIENT_ID: ccloud-springboot-client-941ff9eb-93ff-460d-9d91-8875d40d5664
  OPENAI_API_URL: https://api.openai.com/v1/chat/completions
